### ISSUE TITLE
Please update dsda doom version in MacOS

### ISSUE THREAD

**Issue by Young-Angelo** [Pedro-Beirao/dsda-launcher#11]

**Comment by Pedro-Beirao** [comment]
Yeah I plan on doing this soon.

In the meantime,you can install the latest dsda-doom version using brew

**Comment by Pedro-Beirao** [comment]
Latest release has dsda-doom 0.27.5 (latest dsda-doom version)

https://github.com/Pedro-Beirao/dsda-launcher/releases/tag/v1.3.1
