### ISSUE TITLE
[Feature] Launch histroy

### ISSUE THREAD

**Issue by Vulldozer** [Pedro-Beirao/dsda-launcher#8]
Add a new tab or view where you can see the launch history and launch with the same options you have used previously.

I find myself having to launch the same set of wads and switching back and forth can be annoying, I know you can save and load states but I feel like a history view would simplify the process, and it will help in case you forget to save a state.

Here's a mock-up I made:
![mockup](https://user-images.githubusercontent.com/59207724/193351923-78076be6-b50f-43d9-81c6-ddd2fab9049e.png)

From the technical side of things it would be use the pre-existing state feature, whenever you launch the game it would automatically save a .state file in a history folder/file and the history view would be a data list of those saved .state files.

If you want, you can assigns the issue to me and I will _try_ to implement it

**Comment by Pedro-Beirao** [comment]
![Screenshot 2022-10-01 at 14 26 06](https://user-images.githubusercontent.com/82064173/193411720-36f0107f-f660-4799-bd78-8e4c976f4eda.jpg)

Still very WIP, but it already reads a file called history.states and adds the correct parameters.
I think this is better than having multiple .state files

**Comment by Pedro-Beirao** [comment]
Pushed my work so far.

- It adds to the history whenever you launch the game (If you launch the same parameters multiple times, it will only save it once)
- `Advanced -> History` or `CTRL+Y` to show the history
- Loads the parameters onto the launcher (It cant launch them immediately yet)
- Max of 20 commands are stored (You will be able to change this value on a future commit)

Let me know if you have any problems with it

**Comment by Vulldozer** [comment]
Nice work, I tried the history feature and it works very much like I hoped.
Didn't find any bugs, but I did find one small issue and that is ctrl + y bring up the menu, but clicking ctrl + y a second time doesn't close the menu. would be more convenient if ctrl + y toggled the history menu on and off.

**Comment by Pedro-Beirao** [comment]
I dont think I have ever seen any app that has that behaivior.

To close a window it is usually Ctrl + W. Every window of the launcher already closes with Ctrl + W, except the History, but I can fix that today.

I think using Ctrl + Y as a toggle is not very intuitive
